language: java

matrix:
  include:
    - os: linux
      jdk: oraclejdk11
    - os: osx
      osx_image: xcode10.1 # OSX 10.13, Oracle Java 11
      script: ./gradlew -S --no-daemon --no-parallel build # skip coveralls on MacOS

# The 'build' task runs most things, including test, check, & static analysis
install: true
script:
  - ./gradlew -S --no-daemon --no-parallel build jacocoAggregateReport coveralls
  - ./gradlew -S --no-daemon --no-parallel :npm_run_lint-js

cache:
  directories:
    - $HOME/.npm/
    - $HOME/.gradle/
