language: java

matrix:
  include:
    - os: linux
      dist: trusty
      jdk: oraclejdk8
    - os: linux
      jdk: openjdk8
    - os: osx
      osx_image: xcode9.2 # OSX 10.12, Oracle Java 8
      script: ./gradlew -S --no-daemon --no-parallel build # skip coveralls on MacOS

# The 'build' task runs most things, including test, check, & static analysis
install: true
script:
  - ./gradlew -S --no-daemon --no-parallel build jacocoAggregateReport coveralls
  - ./gradlew -S --no-daemon --no-parallel :npm_run_lint-ci

cache:
  directories:
    - $HOME/.npm/
    - $HOME/.gradle/
