# Default values for chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicas: 1
image:
  registry: andrewstuart
  name: uportal
  tag: "5"

global:
  dnsSuffix: astuart.co
